#!/bin/sh
# Generate cstrike/cs16-moded.cfg and make sure server.cfg execs it LAST.
#
# Why a separate cfg plus an exec line, instead of command-line +cvar args: the engine
# execs server.cfg when the map starts, which is AFTER the command line is processed, so
# `+rcon_password x` loses to `rcon_password ""` on line 2 of PugMod's server.cfg. An
# `exec` appended to the end of server.cfg runs after everything in it, so these values
# win. server.cfg otherwise stays yours -- exactly one managed line is added.
#
# Env:
#   RCON_PASSWORD   explicit password. Unset -> a 32-char random one is generated once
#                   and remembered in cstrike/.rcon_password, so restarts keep it.
#   RCON_ENABLED    set to 0 to skip RCON entirely.
#   GAME_MODE       dm (default) or competitive.
#                   dm: PugMod stays in deathmatch forever -- pug_ready_type 0 disables
#                   the ready system, so a full server no longer auto-starts a match.
#                   competitive: PugMod's own behaviour, ready timer starts a match once
#                   enough players are in.
#   BOTS            1 (default) fills the server with zBot bots, 0 disables them.
#                   The bots are the Condition Zero ones inside ReGameDLL's cs.so. YaPB
#                   ships in the image too but is not loaded -- see docker/install-mods.sh.
#   HUMAN_SLOTS     slots kept free for humans (default 5). Bots default to
#                   MAXPLAYERS - HUMAN_SLOTS.
#   BOT_QUOTA       explicit bot count, overrides the HUMAN_SLOTS calculation
#   BOT_DIFFICULTY  0 easy .. 4 expert (default 3)
#   BOT_AUTOVACATE  1 (default) bots leave to make room for joining humans. YaPB only,
#                   so unused while YaPB is not loaded.
#   BOT_CHATTER     zbot radio chatter: normal (default), minimal, radio, off
#   EXTRA_CVARS     extra console commands, one per line, e.g. "mp_consistency 0"
#   EXTRA_CVARS_FILE  path to a file of the same, appended after EXTRA_CVARS
set -e

HLDS_DIR="${HLDS_DIR:-/opt/hlds}"
CSTRIKE_DIR="$HLDS_DIR/cstrike"
MAXPLAYERS="${MAXPLAYERS:-12}"
HUMAN_SLOTS="${HUMAN_SLOTS:-5}"

# Bots fill everything except the reserved human slots. yb_autovacate frees a SERVER slot
# when a human connects, but it cannot free a TEAM slot -- see the pug_players_max note
# below -- so leaving real room is what actually makes the server joinable.
bot_quota="${BOT_QUOTA:-}"
if [ -z "$bot_quota" ]; then
	bot_quota=$((MAXPLAYERS - HUMAN_SLOTS))
	[ "$bot_quota" -lt 0 ] && bot_quota=0
fi
# zBot difficulty is 0..3; YaPB's is 0..4. BOT_DIFFICULTY is documented on YaPB's scale,
# so clamp it for zBot instead of handing cs.so a value it will not understand.
zbot_difficulty="${BOT_DIFFICULTY:-3}"
case "$zbot_difficulty" in
	''|*[!0-9]*) zbot_difficulty=3 ;;
esac
if [ "$zbot_difficulty" -gt 3 ]; then
	zbot_difficulty=3
fi

GEN_CFG_NAME="cs16-moded.cfg"
GEN_CFG="$CSTRIKE_DIR/$GEN_CFG_NAME"
PW_FILE="$CSTRIKE_DIR/.rcon_password"
MARKER="// added by cs16-moded-server -- runs after everything above, do not remove"

log() {
	echo "[configure] $*"
}

# NOT CALLED. The YaPB cvars, kept beside the zBot ones so switching back is a one-line
# change. YaPB is installed but not loaded, so nothing emits these.
yapb_cvars() {
	echo ""
	echo "// YaPB bots"
	echo "yb_quota \"${bot_quota}\""
	echo "yb_difficulty \"${BOT_DIFFICULTY:-3}\""
	echo "yb_autovacate \"${BOT_AUTOVACATE:-1}\""
	# Bots need a moment after map load before they can be added reliably.
	echo "yb_join_after_player \"0\""
}

mkdir -p "$CSTRIKE_DIR"

# --- rcon password ----------------------------------------------------------

rcon_password=""

if [ "${RCON_ENABLED:-1}" = "0" ]; then
	log "RCON disabled (RCON_ENABLED=0)"
elif [ -n "${RCON_PASSWORD:-}" ]; then
	rcon_password="$RCON_PASSWORD"
	log "RCON password taken from RCON_PASSWORD"
elif [ -s "$PW_FILE" ]; then
	rcon_password=$(cat "$PW_FILE")
	log "RCON password reused from $PW_FILE"
else
	# 32 chars, alphanumeric only: quoting rules in cfg files make punctuation risky.
	rcon_password=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32 || true)
	if [ "${#rcon_password}" -ne 32 ]; then
		log "warning: urandom gave ${#rcon_password} chars, falling back"
		rcon_password=$(date +%s%N | sha256sum | head -c 32)
	fi
	printf '%s' "$rcon_password" > "$PW_FILE"
	chmod 600 "$PW_FILE"
	log "generated a 32-char RCON password (stored in $PW_FILE)"
fi

# --- generate the cfg -------------------------------------------------------

{
	echo "// Generated by cs16-moded-server on every start. Edits here are lost."
	echo "// Put your own settings in server.cfg, or pass EXTRA_CVARS."
	echo ""

	if [ -n "$rcon_password" ]; then
		echo "rcon_password \"$rcon_password\""
	fi

	# PugMod ships pug_ready_type 1 = Automatic (Timer): with pug_players_min 5 per team
	# a server full of bots hits the threshold, pug_ready_time_limit expires, and it leaves
	# deathmatch to run a competitive match on its own. Type 0 disables the ready system
	# entirely, so DM is the resting state and a match only happens when asked for.
	case "${GAME_MODE:-dm}" in
		dm|deathmatch)
			echo ""
			echo "// GAME_MODE=dm -- deathmatch is the default state"
			echo "pug_dm_enable \"1\""
			echo "pug_ready_type \"0\""
			# PugMod caps each team at pug_players_max (ships as 5). Bots fill both teams
			# and a joining human is told "Team Terrorist is already full" even though the
			# server has a free slot. A per-team cap is meaningless in deathmatch, so lift
			# it to the server size and let the engine balance teams.
			echo "pug_players_max \"${MAXPLAYERS}\""
			echo "pug_players_min \"1\""
			;;
		comp|competitive|pug|match)
			echo ""
			echo "// GAME_MODE=competitive -- PugMod ready system runs matches"
			echo "pug_dm_enable \"1\""
			echo "pug_ready_type \"${PUG_READY_TYPE:-1}\""
			;;
		*)
			echo ""
			echo "// GAME_MODE=${GAME_MODE} not recognised -- leaving PugMod defaults"
			;;
	esac

	if [ "${BOTS:-1}" != "0" ]; then
		echo ""
		echo "// zBot -- the Condition Zero bots inside ReGameDLL's cs.so"
		echo "// bot_enable lives in game_init.cfg: cs.so reads it before this file runs."
		echo "bot_quota \"${bot_quota}\""
		echo "bot_quota_mode \"normal\""
		echo "bot_difficulty \"${zbot_difficulty}\""
		echo "bot_join_after_player \"0\""
		echo "bot_join_delay \"0\""
		echo "bot_chatter \"${BOT_CHATTER:-normal}\""
		# The bomb/hostage scenario logic gets in the bots' way in deathmatch.
		case "${GAME_MODE:-dm}" in
			dm|deathmatch) echo "bot_deathmatch \"1\"" ;;
		esac
	fi

	if [ -n "${EXTRA_CVARS:-}" ]; then
		echo ""
		echo "// from EXTRA_CVARS"
		printf '%s\n' "$EXTRA_CVARS"
	fi

	if [ -n "${EXTRA_CVARS_FILE:-}" ] && [ -f "$EXTRA_CVARS_FILE" ]; then
		echo ""
		echo "// from EXTRA_CVARS_FILE ($EXTRA_CVARS_FILE)"
		cat "$EXTRA_CVARS_FILE"
	fi
} > "$GEN_CFG"

# --- make server.cfg exec it, exactly once ----------------------------------

if [ -f "$CSTRIKE_DIR/server.cfg" ]; then
	if grep -q "^exec $GEN_CFG_NAME" "$CSTRIKE_DIR/server.cfg"; then
		log "server.cfg already execs $GEN_CFG_NAME"
	else
		printf '\n%s\nexec %s\n' "$MARKER" "$GEN_CFG_NAME" >> "$CSTRIKE_DIR/server.cfg"
		log "appended 'exec $GEN_CFG_NAME' to server.cfg"
	fi
else
	# No server.cfg at all: the engine execs it if present, so create a minimal one
	# rather than silently dropping our settings.
	printf '%s\nexec %s\n' "$MARKER" "$GEN_CFG_NAME" > "$CSTRIKE_DIR/server.cfg"
	log "no server.cfg found — created one that execs $GEN_CFG_NAME"
fi

# --- tell the operator what happened ----------------------------------------

if [ -n "$rcon_password" ]; then
	log "RCON is ON  ->  rcon_password $rcon_password"
	log "connect: rcon_address <host>:<published udp port>; rcon_password $rcon_password"
fi

case "${GAME_MODE:-dm}" in
	dm|deathmatch)         log "game mode: deathmatch (ready system off, no auto-match)" ;;
	comp|competitive|pug|match) log "game mode: competitive (ready type ${PUG_READY_TYPE:-1})" ;;
	*)                     log "game mode: unknown '${GAME_MODE}' -- PugMod defaults left alone" ;;
esac

if [ "${BOTS:-1}" != "0" ]; then
	log "bots ON (zbot): quota ${bot_quota} of ${MAXPLAYERS} slots (${HUMAN_SLOTS} kept for humans), difficulty ${zbot_difficulty}, chatter ${BOT_CHATTER:-normal}"
else
	log "bots OFF (BOTS=0)"
fi

if [ -n "${EXTRA_CVARS:-}" ]; then
	# if/fi, not `[ -n "$line" ] && log`: EXTRA_CVARS normally ends with a newline, so the
	# last line read is empty, and a false `&&` as the loop's final command would make this
	# pipeline -- and this script -- exit 1. entrypoint.sh runs under `set -e`, so that
	# boot-loops the container right before it hands over to the engine.
	printf '%s\n' "$EXTRA_CVARS" | while read -r line; do
		if [ -n "$line" ]; then
			log "extra: $line"
		fi
	done
fi
